### ISSUE TITLE
Linker errors for OSX framework target.

### ISSUE THREAD

**Issue by cjcaufield** [endikag/libssh2-pod#2]
I'm getting linker errors when building an OSX framework using the libssh2 pod on 10.11.  This happens for any OS X version in the Podfile, and for use_frameworks on or off.

I've created a minimal example repo at: https://github.com/cjcaufield/LIBSSH2Test

Here are the specific errors:

```
Undefined symbols for architecture x86_64:
  "_EVP_aes_128_ctr", referenced from:
      _libssh2_crypt_method_aes128_ctr in libssh2.a(crypt.o)
     (maybe you meant: __libssh2_EVP_aes_128_ctr)
  "_EVP_aes_192_ctr", referenced from:
      _libssh2_crypt_method_aes192_ctr in libssh2.a(crypt.o)
     (maybe you meant: __libssh2_EVP_aes_192_ctr)
  "_EVP_aes_256_ctr", referenced from:
      _libssh2_crypt_method_aes256_ctr in libssh2.a(crypt.o)
     (maybe you meant: __libssh2_EVP_aes_256_ctr)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any help is appreciated.  Thanks for creating this pod.
